# Generated by Django 4.1.3 on 2023-05-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('language', models.CharField(choices=[('Arabic', 'arabic'), ('English', 'english')], max_length=10)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forn_el_batoul.foodcategory')),
            ],
        ),
    ]
