# Generated by Django 4.1.3 on 2023-05-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('english_choice', models.CharField(max_length=64)),
                ('arabic_choice', models.CharField(max_length=64)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forn_el_batoul.foodcategory')),
            ],
        ),
    ]
