# Generated by Django 4.1.3 on 2023-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forn_el_batoul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
