# Generated by Django 4.1.3 on 2023-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forn_el_batoul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='description',
        ),
        migrations.AddField(
            model_name='choice',
            name='arabic_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='english_description',
            field=models.TextField(blank=True),
        ),
    ]
