# Generated by Django 4.1.3 on 2023-05-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forn_el_batoul', '0002_remove_choice_description_choice_arabic_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
