# Generated by Django 4.1.3 on 2023-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forn_el_batoul', '0002_alter_choice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
